Error added

diff --git a/.github/workflows/workflow1.yml b/.github/workflows/workflow1.yml
--- a/.github/workflows/workflow1.yml
+++ b/.github/workflows/workflow1.yml
@@ -20,6 +20,9 @@ jobs:
       - name: Check out repository
         uses: actions/checkout@v4
 
+      - name: To Show Error
+        run: echo "Should fail at this point ..." ; exit 1
+
       # Run a one-line script
       - name: Run a one-line script
         run: echo "Continuous Integration"
